export const LOGIN = 'LOGIN';
export const LOADING = 'LOADING';
export const SET_IMAGE_TO_COMPRESS = 'SET_IMAGE_TO_COMPRESS';
export const SAVE_IMAGE_COMPRESSED = 'SAVE_IMAGE_COMPRESSED';
export const SAVE_IMAGE_COMPRESSED_IN_GALLERY = 'SAVE_IMAGE_COMPRESSED_IN_GALLERY';
